%% setupQuarterCar.m
% Baseline quarter-car suspension setup
%
% This script defines the parameters for the quarter-car suspension
% model and creates the road displacement input used in Simulink. The
% model represents one vehicle corner using:
%
%   - Sprung mass: 1/4 vehicle body corner
%   - Unsprung mass: wheel assembly
%   - Suspension spring and damper
%   - Tire vertical compliance
%   - Road displacement input
%
clear; clc;

%% Masses
Ms = 300;      % Sprung mass, [kg]
Mu = 40;       % Unsprung mass, [kg]

%% Suspension parameters
Ks = 12000;    % Suspension spring stiffness, [N/m]
Cs = 1000;     % Suspension damping coefficient, [N*s/m]

%% Tire parameters
Kt = 190000;   % Tire stiffness, [N/m]
Ct = 100;      % Tire damping coefficient, [N*s/m]

%% Road input setup
% Road profiles are generated by roadSuite.m. Change roadCase to test
% different road inputs: 'speedBump', 'pothole', 'roughRoad',
% 'washboard', 'twoBumps'
roadCase = 'twoBumps';
roadInput = roadSuite(roadCase);